### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by skiasaurus** [mhartl/tau_manifesto#3]
~~[tauclock.com](http://tauclock.com) appears to be defunct. Can't do anything about it until Michael addresses it in the original.~~

~~It's linked to here:~~

~~https://github.com/skiasaurus/tau_manifesto/blob/d4e6e22519518e98b567f25d4d6442bc57eb93b9/chapters/tau_manifesto.tex#L1834~~

Sorry; I meant to create this issue in my fork.

That said, if you'd like to update this on your end, we'll be able to follow. :-)

**Comment by mhartl** [comment]
Thanks. I’ve simply removed the link.
